
class Protocol:
    BUFFER_SIZE = 64
    ENCODING = 'utf-8'

    RECOGNITION_CMD_REQ = 'TILEGAME'
    RECOGNITION_CMD_RES = 'GAMETILE'
    MAPDATA_CMD_REQ = 'MAPDATA'
    MAPDATA_CMD_RES = 'DATAMAP'
    MAPREADY_CMD = 'MAPREADY'
    DISCONNECT_CMD = 'EXIT'
