
class Protocol:
    BUFFER_SIZE = 64
    ENCODING = 'utf-8'

    RECOGNITION_CMD_REQ = 'TILEGAME'
    RECOGNITION_CMD_RES = 'GAMETILE'
    MAPOBJ_CMD_REQ = 'MAPOBJ'
    MAPOBJ_CMD_RES = 'OBJMAP'
    MAPREADY_CMD = 'MAPREADY'
    VERIFY_CMD = 'VERIFY'
    DISCONNECT_CMD = 'BYEBYE'
