
class Protocol:
    BUFFER_SIZE = 64
    ENCODING = 'utf-8'

    RECOGNITION_CMD_REQ = 'TILEGAME'
    RECOGNITION_CMD_RES = 'GAMETILE'
    MAPOBJ_CMD_REQ = 'MAPOBJ'
    MAPOBJ_CMD_RES = 'OBJMAP'
    MAPREADY_CMD = 'MAPREADY'
    PLAYERADD_CMD_REQ = 'HEREIAM'
    PLAYERADD_CMD_RES = 'OKCOMEIN'
    PLAYERADDREADY_CMD = 'AIGHTDONE'
    PLAYERUPDATE_CMD_REQ = 'UPDATEME'
    PLAYERUPDATE_CMD_RES = 'MEUPDATE'
    PLAYERUPDATEREADY_CMD_RES = 'MEUPDATED'
    PLAYERSUPDATE_CMD_REQ = 'UPDATEPLAYERS'
    PLAYERSUPDATE_CMD_RES = 'PLAYERSUPDATE'
    PLAYERSUPDATEREADY_CMD_RES = 'PLAYERUPDATEREADY'
    DISCONNECT_CMD = 'BYEBYE'
